copy only needed files to docker context
GoogleContainerTools/kpt-config-sync pull request #995
Opened 2023-11-03 00:06 UTC by sdowell

This is intended to reduce the time to build the core docker images by only copying needed files into the docker context.

2023-11-03 00:06 UTC, sdowell commented
/assign @karlkfi

2023-11-03 00:15 UTC, karlkfi requested changes
Turns out there's a nifty .dockerignore hack that might work. You can ignore everything and then list exceptions to copy:

```
/**
!/.output/third_party
!/LICENSE
!/go.*
!/cmd
!/clientgen
!/pkg
!/vendor
!/scripts
```

2023-11-03 00:35 UTC, sdowell commented
> Turns out there's a nifty .dockerignore hack that might work. You can ignore everything and then list exceptions to copy:
> 
> ```
> /**
> !/.output/third_party
> !/LICENSE
> !/go.*
> !/cmd
> !/clientgen
> !/pkg
> !/vendor
> !/scripts
> ```

This list won't work for the kind-e2e image/tests, since those copy the e2e testcases into the image to run the tests. We could potentially:
- just copy the `e2e` directory as well for all images
- change the `test-e2e-kind-multi-repo` target to mount the repo into the container rather than copying the repo into the image

2023-11-03 00:43 UTC, karlkfi commented
I suggest changing the kind-e2e image to not COPY anything extra into the image. Just mount the repo dir and go install ./cmd/nomos as part of the test env setup. That way it always uses the local nomos, even if you run it outside of docker.

2023-11-03 21:28 UTC, sdowell commented on build/prow/e2e/Dockerfile
> -COPY . .
Done

2023-11-03 21:31 UTC, karlkfi approved these changes
/lgtm

2023-11-04 02:18 UTC, karlkfi approved these changes
/lgtm

I don't love redecorating the allow list in two places, but I don't think there's any way to cascade them. 

It's a bummer you can't just have a list of dirs in COPY.

2023-11-04 02:18 UTC, merged